name: Test with Nondex
run-name: Known Flaky test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl dmestore-service -am test 
-Dtest=com.huawei.dmestore.services.VmfsOperationServiceImplTest 
-DfailIfNoTests=false
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: 
          mvn -pl dmestore-service -am 
edu.illinois:nondex-maven-plugin:2.1.1:nondex 
-Dtest=com.huawei.dmestore.services.VmfsOperationServiceImplTest 
-DfailIfNoTests=false

